### ISSUE TITLE
Icon viewhelper does not work like expected

### ISSUE THREAD

**Issue by mediaessenz** [quellenform/t3x-iconpack#15] opened 2024-03-15 18:47 UTC
I installed the following Extensions under TYPO3 12:
- bootstrap_package
- iconpack
- bootstrap_package_iconpack
- iconpack_bootstrap

Now i try to use the icon viewhelper inside a template (news) to get a calendar icon of bootstrap:
```html
<html data-namespace-typo3-fluid="true" xmlns:core="TYPO3\CMS\Core\ViewHelpers"
      xmlns:i="http://typo3.org/ns/Quellenform/Iconpack/ViewHelpers"
      xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers">
<i:icon iconfig="bi1:calendar3" preferredRenderTypes="webfont" />
</html>
```

No output is generated.

Also tried different variations:
```
<i:icon iconfig="bi1" additionalAttributes="{class:'calendar3'}" preferredRenderTypes="webfont" />
<i:icon iconfig="bi1:calendar3" additionalAttributes="{class:'calendar3'}" preferredRenderTypes="svgInline,webfont" />
```

Documentation source: https://docs.typo3.org/p/quellenform/t3x-iconpack/1.1/en-us/Tutorials/Usage.html

I would like to add this icon:
https://icons.getbootstrap.com/icons/calendar3/

**Comment by mediaessenz** [comment] 2024-03-15 19:13
Finally I found the right syntax:
```html
<i:icon iconfig="bi1,calendar3" preferredRenderTypes="svgInline" />
```

Would be great, if you could add this to the official docs.

Btw: If I set `preferredRenderTypes="webfont"` I still get no output.

**Comment by stephankellermayr** [comment] 2024-03-15 19:36
First of all, you should note the syntax. 
This is: `iconpack-identifier, icon-identifier, icon-options` (all separated by a comma).

So in this format:

```html
<i:icon iconfig="bi1,calendar3" preferredRenderTypes="webfont" />
```

And the second point could actually have to do with a small bug...

Regarding the frontend, the setting `plugin.tx_iconpack.settings.renderTypes` in the TypoScript setup is decisive, which specifies the order in which the preferences for the output in the frontend should be.

The default order regarding the frontend is: *svgInline, svgSprite, webfont, svg*

I have not yet had this special case in this form in my tests. But obviously there is a conflict between the default setting (which is responsible for all output in the frontend regarding native fields and RTE fields) and the settings that are passed in the ViewHelper.

In any case, you can fix/work around the problem by entering the following code in the TypoScript setup:

```typoscript
plugin.tx_iconpack {
  settings {
    renderTypes {
      bi1 {
        native = webfont
      }
    }
  }
}
```

With this you explicitly achieve that the output should always be in webfont.

However, I'm not sure whether this works for you.

In what form should the output in the frontend generally take place? SVG? SVG inline, or webfont?

**Comment by stephankellermayr** [comment] 2024-03-15 19:39
PS: To be precise: the colon separates the iconpack-identifier from a subset contained in the iconpack (which is the case with Fontawesome, but not with Bootstrap Icons).

**Comment by stephankellermayr** [comment] 2024-03-15 19:44
OK, I have looked again in detail, and in your case the problem is as follows:

The default setting in the frontend specifies that SVG sprites should be used. However, this means that the webfonts (and their CSS) are not automatically loaded in the frontend. However, your ViewHelper wants to display webfonts.

The result:

You get the correct HTML code in the frontend, but the corresponding webfonts or CSS files are not loaded additionally.

In this case, you would have to do this manually, or switch everything to webfonts, or even better: just use SVG sprites (which I would generally recommend).

**Comment by mediaessenz** [comment] 2024-03-18 10:53
Thank you for the explaination.

Is the svg-sprit way working under TYPO3 12?
In the readme it sounds like it's a planned feature: https://github.com/quellenform/t3x-iconpack?tab=readme-ov-file#planned-features

**Comment by stephankellermayr** [comment] 2024-03-18 12:38
@mediaessenz Unfortunately no, there is currently no support for this (even if it has already been partially implemented). Currently (v1.1.2) only webfonts and SVG are supported in CKEditor5.

**Comment by stephankellermayr** [comment] 2024-03-18 12:41
I'm closing this issue for now. Feel free to ask more questions if you have any.

**Closed by stephankellermayr** 2024-03-18 12:41 UTC

**Comment by stephankellermayr** [comment] 2024-03-18 12:48
PS: If you are interested in the problem or even have a solution, here is the issue:  
[CKEditor5: How to integrate a SVG sprite as a widget?](https://stackoverflow.com/questions/77410200/ckeditor5-how-to-integrate-a-svg-sprite-as-a-widget)
