### ISSUE TITLE
iconpack CSS not loaded in news

### ISSUE THREAD

**Issue by grosswerner** [quellenform/t3x-iconpack#22] opened 2024-06-24 09:17 UTC
I have installed the following extension "ICONPACK" for Typo3 version 12, the extension also works as desired with normal content elements.

I then installed the news (11.4.2) extension, the "insert ICON" is displayed in the editor, something is also inserted when I switch to the source code in the editor, as follows

```html
<span class="fas fa-apple-whole" data-iconfig="fa6:solid,apple-whole"></span>
```

been inserted, but the ICON is not displayed in either the frontend or the backend. What else do I have to do to make it work in the NEWS?
Greetings Werner

**Comment by stephankellermayr** [comment] 2024-06-24 09:31
Thank you for your feedback!

You're right, there is something wrong here. Obviously the necessary CSS is not loaded in the backend when editing news records. ...I'll have to take a closer look at this.

However, if you save the record, the icon is still displayed correctly in the frontend.

**Comment by grosswerner** [comment] 2024-06-24 10:59
No, even in the frontend, if you look at the source code of the output page, you can only see the code as in the editor

**Comment by stephankellermayr** [comment] 2024-06-24 12:26
> No, even in the frontend, if you look at the source code of the output page, you can only see the code as in the editor

Have you enabled the `autoConfigRte` and `autoAddAssets` option in the extension settings? ...and have you added the TypoScript correctly?

https://docs.typo3.org/p/quellenform/t3x-iconpack/1.1/en-us/Configuration/Index.html

**Comment by grosswerner** [comment] 2024-06-24 13:06
So I have attached a screenshot regarding your questions, I think I have configured everything accordingly

![Template](https://github.com/quellenform/t3x-iconpack/assets/63292578/e3299721-1c9a-4b37-af62-fc721aca9ab5)
![iconpack](https://github.com/quellenform/t3x-iconpack/assets/63292578/468124a9-fd95-43c9-a112-f008537b72c8)
![Extension](https://github.com/quellenform/t3x-iconpack/assets/63292578/cf9b3a5e-d778-4863-a1c0-eda64db47faf)

and then browser views

![BrowserAnsicht](https://github.com/quellenform/t3x-iconpack/assets/63292578/66c24bea-09b0-4501-b976-184635a5b4d8)
![BrowserSource](https://github.com/quellenform/t3x-iconpack/assets/63292578/b6a97da7-b872-4025-91cb-8b9e4ebdbc51)

**Comment by stephankellermayr** [comment] 2024-06-24 13:35
OK, I see, the transformation from RTE > FE does not seem to be activated here for some reason. Can you please check the value for `$GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][TYPO3\CMS\Core\Html\RteHtmlParser]` under _System > Configuration_?

You should see the following here:
![Bildschirmfoto_2024-06-24_15-30-39](https://github.com/quellenform/t3x-iconpack/assets/2480602/6a393ba5-9fb0-42a9-b042-bcd9947e9c19)

But just to clarify again: This has nothing to do with the topic you mentioned at the beginning.

**Comment by stephankellermayr** [comment] 2024-06-24 14:03
The bug you originally mentioned has just been fixed with version 1.1.6.

- e98e5d8 Switched from PageRenderer to AssetCollector

**Comment by grosswerner** [comment] 2024-06-24 14:07
the following values under System > Configuration?

![Global](https://github.com/quellenform/t3x-iconpack/assets/63292578/bce8067b-7974-4968-92cf-63c33df94c77)

I deleted the cache via the flashes, I even deleted the typotemp
it is the following typo3 version 12.4.16

**Comment by stephankellermayr** [comment] 2024-06-24 14:21
Unfortunately, I cannot reproduce the error with 12.4.16.

It is possible that the problem is related to some individual setup that I cannot analyze without more detailed insight.

But could you please try version 1.1.6 and verify that everything (news) now works in the BE to close this issue?

**Comment by stephankellermayr** [comment] 2024-06-24 14:54
OK, now I'm slowly figuring out what exactly you mean ;-)

In this case, the RTE field of the news data record would also have to be processed via a _DataProcessor_:
https://docs.typo3.org/p/quellenform/t3x-iconpack/main/en-us/Tutorials/Usage.html#rte-fields

Without this, the icons would not be translated by the RteHtmlParser.

I don't have the exact instructions to hand and unfortunately I don't have the time now, but maybe you can figure it out yourself.

**Comment by grosswerner** [comment] 2024-06-25 08:31
I have to admit I'm not a programmer, I can't really do anything with it, I tried the following code for the news teaser
```
    // Add IconpackWizard to the teaser field
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns(
       'tx_news_domain_model_news', [
          'teaser' => [
             'config' => [
                'type' => 'text',
                'renderType' => 'IconpackWizard',
                'rows' => 5,
                'cols' => 40,
                'enableRichtext' => true,
                'richtextConfiguration' => 'default'
             ]
          ]
       ]
    );
```
};

$boot();
unset($boot);



 in the typo3conf/ext/news/Configuration/TCA/Overrides/tx_news_domain_model_news.php, but then the teset field appears in the news maintenance mask. If you would be willing to help me solve this for money.

**Comment by stephankellermayr** [comment] 2024-06-25 15:14
The `IconpackWizard` is only intended for fields that are to provide a single icon directly and not for RTE or text fields. You would need the **DataProcessor** for RTE fields.

What exactly are you trying to do here? Have you enabled an RTE for the teaser field?

**Comment by grosswerner** [comment] 2024-06-25 16:54
In the backend, I have activated the RTE for both the teaser and text fields in the news.
If I insert an icon in one of the above fields in the backend, it works there and I can see the icon.

However, the icon is not displayed in the frontend.
The problem persists, even with the code snippet:

```
# Set templates and dataProcessing
lib.contentElement {
   dataProcessing {
      # This is required to render icons in RTE fields!
      # The output is controlled exclusively by the DataProcessor and then cleaned up by the Sanitizer.
      3212170022 = Quellenform\Iconpack\DataProcessing\IconpackProcessor
      212170022 {
         fieldName = teaser
         fieldType = rte
      }
   }
}
```
My goal is that the ICONS are visible for both the NEWS text and the NEWS teaser in the frontend.

**Comment by stephankellermayr** [comment] 2024-06-26 17:04
Hopefully your second issue has now been resolved with another new version (1.1.7).

I am therefore closing this for now.

Feel free to open a new one at any time if you have any questions.

Also a donation to this project is always welcome and helps to work on further bug fixes and feature requests.

**Closed by stephankellermayr** 2024-06-26 17:04 UTC
Labels: bug

**Comment by ErHaWeb** [comment] 2024-06-28 06:44
I can confirm that the output now works in the context of the news extension (just tested).
Details of my test (in German) can be found here: https://forum.t3academy.de/d/475-extension-iconpack/6

**Comment by grosswerner** [comment] 2024-06-28 08:45
es it works perfectly, thank you
